=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schemas/contributors_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "[unique_identifier_for_this_schema]",
    "title": "Contributors",
    "description": "The Contributors category includes nine metadata fields that identify and give credit to the scientists and organizations involved in the creation of the dataset.",
    "type": "array",
		"uniqueItems": true,
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "contributorName": {
                "description": "Person (last name, first name) or organization (e.g., research group, department, institution) contributing to or responsible for the project, but does not include funders of the project.",
                "type": "string"
            },
            "Creator": {
                "description": "Main researchers involved in producing the data. There must be at least one creator.",
                "type": "string",
                "enum": ["Yes", "No"]
            },
            "contributorType": {
                "description": "Categorization of the role of the contributor. Recommended: ProjectLeader (for principal investigator), ResearchGroup (for lab, department, or division).",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["ContactPerson", "DataCollector", "DataCurator", "ProjectLeader", "ProjectManager", "ProjectMember", "RelatedPerson", "Researcher", "ResearchGroup", "Other"]
                }
                            },
            "nameType": {
                "description": "Type of contributor.",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["Organizational", "Personal"]
                }
            },
            "nameIdentifier": {
                "description": "Alphanumeric code that uniquely identifies an individual or legal entity, (listed in the contributorName field). Accepted identifiers include GRID, ISNI, ORCID, ROR, and RRID. Preferred identifiers are ORCID for personal names and ROR for organizational names.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "nameIdentifierScheme": {
                "description": "Identifying scheme used in nameIdentifier.",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["GRID", "ISNI", "ORCID", "ROR", "RRID"]
                }

            },
            "affiliation": {
                "description": "Organizational or institutional affiliation of the contributor.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "affiliationIdentifier": {
                "description": "Unique identifier (ROR preferred) for the organizational or institutional affiliation of the contributor.",
                "type": "array",
                "items": {
                    "type": "string"
                }

            },
            "affiliationIdentifierScheme": {
                "description": "Identifying scheme used in affiliationIdentifier.",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["GRID", "ISNI", "ORCID", "ROR", "RRID"]
                }
            }
        },
        "if": {
            "properties": {
                "nameType": {
                    "const": "Personal"
                }
            }
        },
        "then": {
            "required": ["contributorName", "Creator", "contributorType", "nameType", "nameIdentifier", "nameIdentifierScheme", "affiliation", "affiliationIdentifier", "affiliationIdentifierScheme"]
        },
        "else": {
            "required": ["contributorName", "Creator", "contributorType", "nameType", "nameIdentifier", "affiliation", "affiliationIdentifier", "affiliationIdentifierScheme"]
        }
    }
}

=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schema_tests/120121/original_input/contributors_test.json
[
		{
			"contributorName": "Your Name",
			"Creator": "Yes",
			"contributorType": ["Researcher"],
			"nameType": ["Personal"],
			"nameIdentifier": ["YN"],
			"nameIdentifierScheme": ["GRID"],
			"affiliation": ["Also YN"],
			"affiliationIdentifier": ["AYN"],
			"affiliationIdentifierScheme": ["GRID"]
		},
		{
			"contributorName": "Your Name 2",
			"Creator": "Yes",
			"contributorType": ["Researcher", "ProjectLeader"],
			"nameType": ["Personal", "Organizational"],
			"nameIdentifier": ["YN"],
			"nameIdentifierScheme": ["GRID", "ROR", "RRID"],
			"affiliation": ["Also YN", "Another"],
			"affiliationIdentifier": ["AYN"],
			"affiliationIdentifierScheme": ["ISNI", "ORCID"]
		}
	]
