=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schemas/image_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "IMAGE",
    "title": "Image",
    "description": "The Image category includes 33 metadata fields that describe the size and 3-dimensional orientation of the image, the channels and fluorophores used, and the location of relevant landmarks.",
		"type": "object",
		"required": ["xAxis","yAxis","zAxis","Number","displayColor","stepSizeX","stepSizeY"],
        "additionalProperties": false,
		"properties": {
				"xAxis": {
						"description": "Predominant tissue direction as one moves from the left side of the image to the right side of the image.",
						"type": "string",
						"enum": ["Left-to-right", "Right-to-left", "Anterior-to-posterior", "Posterior-to-anterior", "Inferior-to-superior", "Superior-to-inferior", "Oblique"]
				},
				"obliqueXDim1": {
						"description": "Only if xAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Left","Right"]
				},
				"obliqueXDim2": {
						"description": "Only if xAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Anterior","Posterior"]
				},
				"obliqueXDim3": {
						"description": "Only if xAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Inferior","Superior"]
				},
				"yAxis": {
						"description": "Predominant tissue direction as one moves from the top of the image to the bottom of the image.",
						"type": "string",
						"enum": ["Left-to-right", "Right-to-left", "Anterior-to-posterior", "Posterior-to-anterior", "Inferior-to-superior", "Superior-to-inferior", "Oblique"]
				},
				"obliqueYDim1": {
						"description": "Only if yAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Left","Right"]
				},
				"obliqueYDim2": {
						"description": "Only if yAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Anterior","Posterior"]
				},
				"obliqueYDim3": {
						"description": "Only if yAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Inferior","Superior"]
				},
				"zAxis": {
						"description": "Predominant tissue direction as one follows a given pixel position through the stack of images from the first image to the last image.",
						"type": "string",
						"enum": ["Left-to-right", "Right-to-left", "Anterior-to-posterior", "Posterior-to-anterior", "Inferior-to-superior", "Superior-to-inferior", "Oblique"]
				},
				"obliqueZDim1": {
						"description": "Only if zAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Left","Right"]
				},
				"obliqueZDim2": {
						"description": "Only if zAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Anterior","Posterior"]
				},
				"obliqueZDim3": {
						"description": "Only if zAxis is oblique, enter the orientation.",
						"type": "string",
						"enum": ["Inferior","Superior"]
				},
				"landmarkName": {
						"description": "Name of the landmark (e.g., bregma).",
						"type": "string"
				},
				"landmarkX": {
						"description": "X coordinate of the landmark.",
						"type": "number"
				},
				"landmarkY": {
						"description": "Y coordinate of the landmark.",
						"type": "number"
				},
				"landmarkZ": {
						"description": "Z coordinate of the landmark.",
						"type": "number"
				},
				"Number": {
						"description": "Number assigned to each channel.",
						"type": "number"
				},
				"displayColor": {
						"description": "Display color of each channel in triplet (red, green, blue) format.",
						"type": "array",
						"items": {
							"type": "string"
						}

				},
				"Representation": {
						"description": "What the channel represents (e.g., rhodopsin, virus).",
						"type": "string"
				},
				"Flurophore": {
						"description": "Fluorophore used in the channel (e.g., egfp, alexa-561, ATO-647). ",
						"type": "string"
				},
				"stepSizeX": {
						"description": "Physical step size in the X-dimension (e.g., pixel size represents the number of microns).",
						"type": "string"
				},
				"stepSizeY": {
						"description": "Physical step size in the Y-dimension (e.g., pixel size represents the number of microns).",
						"type": "string"
				},
				"stepSizeZ": {
						"description": "Distance between the center of one image and the center of adjacent images in the Zdimension (space in microns between slices).",
						"type": "string"
				},
				"stepSizeT": {
						"description": "Physical step size in the T dimension (time).",
						"type": "string"
				},
				"Channel": {
						"description": "Number of channels.",
						"type": "number"
				},
				"Slices": {
						"description": "Number of slices per channel (approximate).",
						"type": "number"
				},
				"t": {
						"description": "Number of timepoints.",
						"type": "number"
				},
				"xSize": {
						"description": "Number of pixels in the X-dimension.",
						"type": "number"
				},
				"ySize": {
						"description": "Number of pixels in the Y-dimension.",
						"type": "number"
				},
				"zSize": {
						"description": "Number of pixels in the Z-dimension.",
						"type": "number"
				},
				"Gbyte": {
						"description": "Total size in gigabytes.",
						"type": "number"
				},
				"File": {
						"description": "Total number of image files.",
						"type": "number"
				},
				"dimensionOrder": {
						"description": "XYZT, or whatever order is used.",
						"type": "string"
				}
		},
		"allOf": [{
						"if": {
								"properties": {
										"xAxis": {
												"const": "Oblique"
										}
								},
								"required": ["xAxis"]
						},
						"then": {
								"required": ["obliqueXDim1","obliqueXDim2","obliqueXDim3"]
						}
				}, {
						"if": {
								"properties": {
										"yAxis": {
												"const": "Oblique"
										}
								},
								"required": ["yAxis"]
						},
						"then": {
								"required": ["obliqueYDim1","obliqueYDim2","obliqueYDim3"]
						}
				},{
						"if": {
								"properties": {
										"zAxis": {
												"const": "Oblique"
										}
								},
								"required": ["zAxis"]
						},
						"then": {
								"required": ["obliqueZDim1","obliqueZDim2","obliqueZDim3"]
						}
				}
		]
}

=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schema_tests/120121/original_input/image_test.json
{
		"xAxis": "Oblique",
		"obliqueXDim1": "Left",
		"obliqueXDim2": "Anterior",
		"obliqueXDim3": "Inferior",
		"yAxis": "Left-to-right",
		"obliqueYDim1": "Left",
		"obliqueYDim2": "Anterior",
		"obliqueYDim3": "Inferior",
		"zAxis": "Anterior-to-posterior",
        "obliqueZDim1": "Right",
		"obliqueZDim2": "Posterior",
		"obliqueZDim3": "Superior",
        "landmarkX": 5,
        "landmarkY": 20,
        "landmarkZ": 2,
		"Number": 10,
		"displayColor": ["red","blue"],
        "Representation": "rhodopsin",
        "Flurophore": "egfp",
		"stepSizeX": "",
		"stepSizeY": "",
        "stepSizeZ": "",
        "stepSizeT": "",
        "Channel": 3,
        "Slices": 4,
        "t": 3,
        "xSize": 20,
        "ySize": 30,
        "zSize": 40,
        "Gbyte": 2.1,
        "File": 3.2,
        "dimensionOrder": "XYZT"
	}
