=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schemas/publication_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "PUBLICATIONS",
    "title": "Publications",
    "description": "The Publication category includes five optional metadata fields that identify publications, pre-prints, and protocols that are related to the dataset. ",
    "type": "array",
		"uniqueItems": true,
    "items": {
        "type": "object",
        "properties": {
            "relatedIdentifier": {
                "description": "Alphanumeric code that uniquely identifies the publication or other related information.",
                "type": "array",
                "items": {
                    "type": "string"
                }

            },
            "relatedIdentifierType": {
                "description": "Identifying scheme used in relatedIdentifier. Recommended: DOI, PMID.",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["arXiv", "DOI", "ISBN", "PMID"]
                }

            },
            "PMCID": {
                "description": "PubMed Central identifier (PMCID; if applicable).",
                "type": "array",
                "items": {
                    "type": "string"
                }

            },
            "relationType": {
                "description": "DataCite descriptive identifier specifying the relationship. Recommended: IsCitedBy (for publications), IsDocumentedBy (for protocols).",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["IsCitedBy", "IsDocumentedBy"]
                }
            },
            "Citation": {
                "description": "Complete citation for the publication or other related information.",
                "type": "string"
            }
        },
    "additionalProperties": false
    }
}

=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schema_tests/120121/original_input/publication_test.json
[{
        "relatedIdentifier":["HI", "HI2"],
        "relatedIdentifierType": ["arXiv"],
        "PMCID": ["id1"],
        "relationType": ["IsCitedBy"],
        "Citation": "citationExample"
    },
		{
        "relatedIdentifier": ["HI3"],
        "relatedIdentifierType": ["DOI", "ISBN"],
        "PMCID": ["id1", "id2"],
        "relationType": ["IsDocumentedBy"],
        "Citation": "citationExample2"
    }
]
