=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schemas/120121/oniginal_input/dataset_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "[unique_identifier_for_this_schema]",
    "title": "Dataset",
    "description": "The Dataset category includes 14 metadata fields that provide a high-level description of the data including title, abstract, methods, imaging modality, and how the data can be reused.",
		"type": "object",
		"required": ["Title","Rights","rightsURI","rightsIdentifier","Abstract"],
        "additionalProperties": false,
		"properties": {
				"Title": {
						"description": "Short phrase by which the specific dataset is known (e.g., title of a book).",
						"type": "string"
				},

				"socialMedia": {
						"description": "Suggested short social media text describing the dataset to be posted after the dataset is available (can include tags). May be same as the title.",
						"type": "string"
				},

				"Subject": {
						"description": "Description of the dataset using keywords, classification codes, or key phrases.",
						"type": "string"
				},

				"subjectScheme": {
						"description": "Name of subject scheme or classification (e.g., Allen Mouse Brain Atlas Version2).",
						"type": "string"
				},

				"Rights": {
						"description": "Any rights information for the dataset. May be the name of the license and can include embargo or other use restrictions on data (see https://spdx.org/licenses).",
						"type": "string"
				},

				"rightsURI": {
						"description": "If using a common license and licensing information is online, provide a link to the license.",
						"type": "string"
				},

				"rightsIdentifier": {
						"description": "If using a common license, provide the Software Package Data Exchange (SPDX) code for the license (see https://spdx.org/licenses).",
						"type": "string"
				},

				"Image": {
						"description": "Suggested static image or animated GIF to associate with the social media and/or web landing page for the dataset.",
						"type": "string"
				},

				"generalModality": {
						"description": "Description of the general modality of the dataset.",
						"type": "string",
						"enum": ["Cell morphology", "Connectivity", "Population imaging", "Spatial", "transcriptomics", "Other"]
				},

				"generalModalityOther": {
						"description": "If generalModality is Other, list the modality used.",
						"type": "string"
				},

				"Technique": {
						"description": "Description of the technique used.",
						"type": "string",
						"enum": ["Anterograde tracing", "DARTFISH", "fMOST", "MERFISH", "Patch-seq", "Retrograde", "Retrograde tracing", "smFISH", "Transynaptic tracing", "TRIO tracing", "Other"]
				},

				"techniqueOther": {
						"description": "If Technique is Other, list the technique used.",
						"type": "string"
				},

				"Abstract": {
						"description": "Additional descriptive information about the dataset, including a brief description and the context in which it was created (e.g., aim of the experiment, what the dataset is expected to show). This abstract will be used on the Digital Object Identifier (DOI) landing page and will be the primary description of the dataset; ideally 100+ words.",
						"type": "string"
				},

				"Methods": {
						"description": "Additional descriptive information about how the biological materials were processed by the laboratories involved. May be used to describe the methodology (or protocols) used.",
						"type": "string"
				},

				"technicalInfo": {
						"description": "Additional descriptive information about how the data was processed computationally by the laboratories involved. May be used to describe the computational processing done with software versions and parameters. ",
						"type": "string"
				}
		},
		"allOf": [{
						"if": {
								"properties": {
										"generalModality": {
												"const": "Other"
										}
								},
								"required": ["generalModality"]
						},
						"then": {
								"required": ["generalModalityOther"]
						}
				}, {
						"if": {
								"properties": {
										"Technique": {
												"const": "Other"
										}
								},
								"required": ["Technique"]
						},
						"then": {
								"required": ["techniqueOther"]
						}
				}
		]
}

=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schema_tests/dataset_test.json
{
		"Title": "title of a book",
		"socialMedia": "title of a book",
		"Subject": "classificationCode21",
		"subjectScheme": "Allen Mouse Brain Atlas",
		"Rights": "license45a",
		"rightsURI": "https://spdx.org/licenses",
		"rightsIdentifier": "SPDX90",
		"Image": "imageExample",
		"generalModality": "Other",
        "generalModalityOther": "modality1",
		"Technique": "Other",
        "techniqueOther": "smFISH2",
		"Abstract": "Pesticide (fenthion) which finds its way into water bodies, bring about physiological changes in aquatic animals, via histomorphology and histopathology of various tissues. In fishes, it induces disorders including hyposecretion of gonadotropin in the PPD and regression of gonads. Light microscopic studies were made on control and treated pituitary (gonadotropin secreting cells-GTH) and testis of Glossogobius giuris (HAM) during spawning phase after exposing them to different (0.05 to 0.5 ppm) sub-lethal concentration of fenthion for a short-term period (24 to 96 hrs). The results indicated alteration in normal histology of gonadotropin secreting cells and testis, reduction in number of sperms and degranulation of GTH cells under light microscopy. Degeneration and fragmentation of cytoplasmic organelles was noticed in GTH cells under electron microscope, with the increase in the sub-lethal concentration of fenthion. Significance of the results is discussed in detail in the manuscript.",
		"Methods": "imaging method 2",
		"technicalInfo": "version2"
	}

=== Defining-Our-Research-Methodology-DORy/3D-Microscopy-Metadata-Standards-3D-MMS/input_files/dataset_test.json
{
		"Title": "",
		"socialMedia": "",
		"Subject": "",
		"subjectScheme": "",
		"Rights": "",
		"rightsURI": "",
		"rightsIdentifier": "",
		"Image": "",
		"generalModality": "Other",
		"generalModalityOther": "",
		"Technique": "Other",
		"techniqueOther": "",
		"Abstract": "",
		"Methods": "",
		"technicalInfo": ""
	}
